/*
SQLyog Community v12.5.1 (64 bit)
MySQL - 5.7.21-enterprise-commercial-advanced-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `data` (
	`id` int (11),
	`machineQrCode` varchar (765),
	`token` varchar (765),
	`shift` varchar (765),
	`createdAt` date ,
	`toolMounted` tinyint (1),
	`machineStopped` tinyint (1),
	`barcodeProductionNo` int (11),
	`cavity` int (11),
	`cycleTime` varchar (765),
	`partStatus` tinyint (1),
	`pieceNumber` int (11),
	`note` varchar (765),
	`toolCleaning` tinyint (1),
	`remainingProductionTime` int (11),
	`remainingProductionDays` int (11),
	`operatingHours` varchar (765)
); 
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('6','Emac50-1 ','0004650166692','S2','2024-05-14','0','0','811202001','4','13,1','1','27656','.','1','840','2','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('8','KM50-1','0004650166692','S2','2024-05-14','0','0','809216001','4','33,2','1','11276','.','1','660','1','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('15','F450iA-1','04711227280','F1','2024-05-15','0','0','811362002','1','178','1','192','','1','0','2','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('16','Emac50-1','04711227280','F1','2024-05-15','0','0','811202001','4','13,1','1','45116','','1','1200','1','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('17','KM 50-1','04711227280','F1','2024-05-15','0','0','809216001','4','33,3','1','17988','','0','1110','0','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('18','E 55-1','04711227280','F1','2024-05-15','0','0','811197001','32','14,2','1','2171904','','0','1320','0','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('19','E 35-1','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('20','E 45-2','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('21','E 45-2','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('22','E 45-1','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('23','E 50-2','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('24','E50-3','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('25','Emac50-2','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('26','Emac50-3 ','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('27','E 50-3','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('28','F150iA-1','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('29','E 80-1','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('30','E 120-1','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('31','KM 150-1','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('32','KM 80-1','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('33','KM 420-1','04711227280','F1','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('34','F450iA-1','04711227280','S2','2024-05-15','0','0','811362002','1','178','1','352','','0','780','1','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('35','E 35-1','04711227280','S2','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('36','E 45-2','04711227280','S2','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('37','E 45-1','04711227280','S2','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('38','E 50-2','04711227280','S2','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('39','E 50-3','04711227280','S2','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('40','Emac50-1','04711227280','S2','2024-05-15','0','0','811202001','4','13,1','1','53844','','0','900','1','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('41','Emac50-2','04711227280','S2','2024-05-15','0','0','811265001','8','12,6','1','2920','','1','300','1','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('42','Emac50-3','04711227280','S2','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('43','F150iA-1','04711227280','S2','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('44','E 80-1','04711227280','S2','2024-05-15','0','0','811289001','4','16,5','1','664','','0','1020','0','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('45','F250iA-1','04711227280','S2','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('46','E 120-1','04711227280','S2','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('47','KM 420-1','04711227280','S2','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('48','E 55-1','04711227280','S2','2024-05-15','0','0','811197001','32','16,2','1','2238976','','0','1200','0','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('49','KM 150-1','04711227280','S2','2024-05-15','0','0','811362005','1','150','1','1','WZ zur Aufnahme gerade angefangen ','0','0','1','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('50','KM 80-1','04711227280','S2','2024-05-15','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('51','KM 50-1','04711227280','S2','2024-05-15','0','0','809216001','4','33,7','1','20116','','0','840','0','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('52','F450iA-1','04711227280','F1','2024-05-16','0','0','811362002','1','178','1','723','','1','1140','0','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('53','E 45-2','04711227280','F1','2024-05-16','0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('54','E 35-1','04711227280','F1','2024-05-16','0','0','811471001','4','14,9','1','16660','','1','570','0','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('55','E 45-1','04711227280','F1','2024-05-16','1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('56','E 50-2','04711227280','F1','2024-05-16','1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('57','E 50-3','04711227280','F1','2024-05-16','1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('58','Emac50-1','04711227280','F1','2024-05-16','0','0','811202001','4','13,1','1','74224','','1','1208','0','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('59','Emac50-2','04711227280','F1','2024-05-16','0','0','811265001','8','12,6','1','45424','','1','687','0','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('60','Emac50-3','04711227280','F1','2024-05-16','1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('61','F150iA-1','04711227280','F1','2024-05-16','1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('62','E 80-1','04711227280','F1','2024-05-16','0','0','811289001','4','16,5','1','3472','','1','795','0','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('63','E 120-1','04711227280','F1','2024-05-16','1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('64','E 55-1','04711227280','F1','2024-05-16','0','0','811197001','32','14,2','1','2380992','','1','88','0','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('65','KM 150-1','04711227280','F1','2024-05-16','0','0','811362005','1','101','1','680','','1','771','0','00:00');
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('66','KM 80-1','04711227280','F1','2024-05-16','1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('67','KM 50-1','04711227280','F1','2024-05-16','1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('68','KM 420-1','04711227280','F1','2024-05-16','1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `data` (`id`, `machineQrCode`, `token`, `shift`, `createdAt`, `toolMounted`, `machineStopped`, `barcodeProductionNo`, `cavity`, `cycleTime`, `partStatus`, `pieceNumber`, `note`, `toolCleaning`, `remainingProductionTime`, `remainingProductionDays`, `operatingHours`) values('69','F250iA-1','04711227280','F1','2024-05-16','1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
